name: Start EC2 Instance

on: workflow_dispatch


jobs:
  StartInstance:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Fetch Code
        uses: actions/checkout@v4

      - name: Setup Python ENV
        uses: actions/setup-python@v5
        with: 
          version: '3.10'

      - name: Install Packages
        run: pip install -r requirements.txt
      
      - name: Get AWS Permissions
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::975050176956:role/ec2ghactionstartstop

      - name: Start Instance
        run: python start.py