name: Stop EC2 Instance

on: workflow_dispatch


jobs:
  StopInstance:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_ARN_ROLE: ${{ secrets.AWS_ARN_ROLE }}
      AWS_INSTANCE_NAME: ${{ secrets.EC2_INSTANCE_NAME }}

    steps:
      - name: Fetch Code
        uses: actions/checkout@v4

      - name: Setup Python ENV
        uses: actions/setup-python@v5
        with: 
          version: '3.10'

      - name: Install Packages
        run: pip install -r requirements.txt
      
      - name: Get AWS Permissions
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: $AWS_ARN_ROLE

      - name: Stop Instance
        run: python stop.py

      - name: Echo Steps
        run: echo " ${{ steps }}"